version: '3'
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    depends_on:
      - backend
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - database
  database:
    image: "h2database/h2:latest"
    ports:
      - "9092:9092"
    environment:
      - H2_OPTIONS=-ifNotExists
