services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - maven-cache:/root/.m2
      - ./back/src/main/resources/assets/uploads:/app/images

volumes:
  maven-cache:
